### ISSUE TITLE
Memory leaks from using as_slice

### ISSUE THREAD

**Issue by gchp** [dlaronson/gapbuffer#8]
Gapbuffer is leaking memory from here: https://github.com/dlaronson/gapbuffer/blob/master/src/lib.rs#L290-L310

This is allocating memory and returning a slice which means the slice will leak since slices are non-owning.

We discussed this in Iota's gitter channel earlier, and think that the best solution would be to remove the `as_slice` usage. This would mean removing the `Index<Range>` traits, and re-writing the `Index<usize>` trait to use something other than `as_slice`.

@pythonesque, @Crespyl, @utkarshkukreti feel free to add anything else from the discussion here.

**Comment by pythonesque** [comment]
To clarify a bit further: we could still have slicing but we'd have to create a special slice type that worked for gap buffers.

Also, a good rule of thumb is that because they are implicit, `Deref` implementations should not perform any nontrivial operations (allocation and looping _definitely_ count as nontrivial!).  Treat them like you would code protected by a spinlock.  In this case, I don't think we want a `Deref` implementation at all; `Vec` is a special case among collections in having one.

On a related note, I think we should rip out the guts of GapBuffer (removing all uses of `unsafe` in the process) and use a `Vec` instead of a raw pointer.  I don't think there's any performance advantage to not using a plain `Vec` as the backing buffer here (we can always use `unsafe_get()` to make sure we don't double-bounds-check if we need to, but I'd wait to do for the time being), and less unsafe code => less time messing around with valgrind.

**Comment by withoutboats** [comment]
Yeah, I'll rewrite it to use vec.

**Comment by pythonesque** [comment]
@dlaronson I'm actually almost done with a rewrite to use a `RingBuf`.  Otherwise we will have problems moving out of elements, plus the current implementation looks like it's actually derived from `RingBuf` in the first place (BTW, the current version does not have a `Drop` implementation, which makes it not work anyway for types with destructors).

**Comment by withoutboats** [comment]
Great, that's what I had already moved towards (& its where I originally 
started before I decided to implement all the unsafe code myself).
